# Generated by Django 3.2.5 on 2021-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('poetries', '0004_alter_like_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'profile')},
        ),
    ]
