# Generated by Django 3.2.5 on 2021-07-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0005_auto_20210718_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('poetry', 'poetry'), ('reflection', 'reflection'), ('real_story', 'real_story'), ('I_read_you', 'I_read_you')], default='poetry', max_length=20),
        ),
    ]
