# Generated by Django 3.2.5 on 2021-07-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('poetries', '0006_alter_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterPostsType', models.CharField(choices=[('poetry', 'poetry'), ('reflection', 'reflection'), ('real_story', 'real_story'), ('I_read_you', 'I_read_you')], default='poetry', max_length=20)),
                ('happy', models.BooleanField(default=False)),
                ('sad', models.BooleanField(default=False)),
                ('normal', models.BooleanField(default=False)),
                ('action', models.BooleanField(default=False)),
                ('romance', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
