# Generated by Django 3.2.5 on 2021-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0011_auto_20210731_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='bg_color',
            field=models.CharField(choices=[('default_color_bg', 'css/default_color_bg.css'), ('purple_color_bg', 'css/purple_color_bg.css')], default='default_color_bg', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='theme_color',
            field=models.CharField(choices=[('default_colors_theme', 'css/default_colors_theme.css'), ('green_colors_theme', 'css/green_colors_theme.css'), ('golden_colors_theme', 'css/golden_colors_theme.css'), ('bold_brown_colors_theme', 'css/bold_brown_colors_theme.css'), ('light_blue_colors_theme', 'css/light_blue_colors_theme.css'), ('black_colors_theme', 'css/black_colors_theme.css'), ('light_green_colors_theme', 'css/light_green_colors_theme.css'), ('oily_colors_theme', 'css/oily_colors_theme.css'), ('blue_colors_theme', 'css/blue_colors_theme.css'), ('brown_colors_theme', 'css/brown_colors_theme.css')], default='default_color_bg', max_length=50),
        ),
    ]
