# Generated by Django 3.2.5 on 2021-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0012_auto_20210731_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='bg_color',
            field=models.CharField(choices=[('css/default_color_bg.css', 'default_color_bg'), ('css/purple_color_bg.css', 'purple_color_bg')], default='default_color_bg', max_length=50),
        ),
    ]
