# Generated by Django 3.2.5 on 2021-08-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0014_alter_color_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='bg_color',
            field=models.CharField(choices=[("{% static 'css/default_color_bg.css'%}", "{% static 'css/default_color_bg.css'%}"), ("{% static 'css/purple_color_bg.css'%}", "{% static 'css/purple_color_bg.css' %}")], default='default_color_bg', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='theme_color',
            field=models.CharField(choices=[("{% static 'css/default_colors_theme.css'%}", "{% static 'css/default_colors_theme.css'%}"), ("{% static 'css/green_colors_theme.css'%}", "{% static 'css/green_colors_theme.css'%}"), ("{% static 'css/golden_colors_theme.css'%}", "{% static 'css/golden_colors_theme.css'%}"), ("{% static 'css/bold_brown_colors_theme.css'%}", "{% static 'css/bold_brown_colors_theme.css'%}"), ("{% static 'css/light_blue_colors_theme.css'%}", "{% static 'css/light_blue_colors_theme.css'%}"), ("{% static 'css/black_colors_theme.css'%}", "{% static 'css/black_colors_theme.css'%}"), ("{% static 'css/light_green_colors_theme.css'%}", "{% static 'css/light_green_colors_theme.css'%}"), ("{% static 'css/oily_colors_theme.css'%}", "{% static 'css/oily_colors_theme.css'%}"), ("{% static 'css/blue_colors_theme.css'%}", "{% static 'css/blue_colors_theme.css'%}"), ("{% static 'css/blue_colors_theme.css'%}", "{% static 'css/blue_colors_theme.css'%}")], default='default_color_bg', max_length=50),
        ),
    ]
