# Generated by Django 3.2.5 on 2021-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0015_auto_20210802_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='bg_color',
            field=models.CharField(choices=[('default_color_bg', 'default_color_bg'), ('purple_color_bg', 'purple_color_bg')], default='default_color_bg', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='theme_color',
            field=models.CharField(choices=[('default_colors_theme', 'default_colors_theme'), ('green_colors_theme', 'green_colors_theme'), ('golden_colors_theme', 'golden_colors_theme'), ('bold_brown_colors_theme', 'bold_brown_colors_theme'), ('light_blue_colors_theme', 'light_blue_colors_theme'), ('black_colors_theme', 'black_colors_theme'), ('light_green_colors_theme', 'light_green_colors_theme'), ('oily_colors_theme', 'oily_colors_theme'), ('blue_colors_theme', 'blue_colors_theme'), ('blue_colors_theme', 'blue_colors_theme')], default='default_color_bg', max_length=50),
        ),
    ]
